gitlab:
  projects: "./gitlab/projects"
  outputs: "./gitlab/outputs"
  variables: "./gitlab/variables"
  workers: 10

github:
  projects: "./github/projects"
  workflows: "./github/workflows"
  workers: 10
  pagesize: 10

sonarqube:
  projects: "./sonarqube/projects"
  issues: "./sonarqube/issues"

registry:
  images: "./registry/images"
  commands: "./registry/commands"
  workers: 10

jenkins:
  outputs: "./jenkins/outputs"
  artifacts: "./jenkins/artifacts"

nexus:
  repositories: "./nexus/repositories"

azure:
  artifacts: "./azure/artifacts/"
  projects: "./azure/projects/"
  logs: "./azure/logs/"
  variables: "./azure/variables/"

horusec:
  path: "/path/to/horusec_binary"

trufflehog:
  path: "/path/to/trufflehog_binary"

gitea:
  projects: "./gitea/projects"

artifactory:
  repositories: "./artifactory/repositories"
  docker: "./artifactory/docker"
  workers: 10